In [6]:
#1
import numpy as np
array=np.random.randint(2, 10, size=(2,4))
print(array)
array.tolist()

[[4 6 9 6]
 [9 7 9 6]]


[[4, 6, 9, 6], [9, 7, 9, 6]]

In [7]:
#2
import numpy as np
a=np.random.randint(0,10,size=(4,4))
print(a)
result =  np.trace(a)
print("Condition number of the said matrix: ")
print(result)

[[2 1 0 8]
 [6 8 8 6]
 [5 7 8 2]
 [8 6 4 7]]
Condition number of the said matrix:
25


In [8]:
#3
x=2
import numpy as np
a=np.random.randint(2,10,size=(3,5))
print(a)
b=int(input("give a number: "))
for i in a:
    for c in i:
        if c>b:
            print(c)
print(c)    

[[4 7 3 7 3]
 [6 3 3 8 5]
 [6 8 6 2 5]]
give a number: 5
7
7
6
8
6
8
6
5


In [13]:
#4
import numpy as np
x=np.random.randint(2,10,size=(2,2))
y=np.random.randint(2,10,size=(2,2))
print(x)
print(y)
C=x+y
print(C)

[[5 8]
 [5 2]]
[[2 7]
 [4 5]]
[[ 7 15]
 [ 9  7]]


In [5]:
#5
import numpy as np
print("Original matrix: ")
a= np.random.randint(0, 10,(2,4))
print(a)
print("Subtract the mean of each row of the said matrix: ")
b = a- a.mean(axis=0, keepdims=True)
print(b)

Original matrix: 
[[2 0 4 7]
 [3 0 3 7]]
Subtract the mean of each row of the said matrix: 
[[-0.5  0.   0.5  0. ]
 [ 0.5  0.  -0.5  0. ]]
